version: "3.9"

services:
  server:
    build:
      context: ./
    ports:
      - '8081:8081'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 2s
      timeout: 30s
      retries: 10

volumes:
  my-db:
